{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: telcopulse-app
  labels:
    app.kubernetes.io/part-of: telcopulse
automountServiceAccountToken: false
{{- end }}
