package events

import (
	"context"
	"github.com/twmb/franz-go/pkg/kgo"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/propagation"
	"go.opentelemetry.io/otel/trace"
)

// TraceParent serializes only W3C trace identity, never baggage or application data.
func TraceParent(ctx context.Context) string {
	carrier := propagation.MapCarrier{}
	propagation.TraceContext{}.Inject(ctx, carrier)
	return carrier.Get("traceparent")
}

func traceContext(ctx context.Context, parent string) context.Context {
	// Version 00 generated by our SDK is exactly 55 characters. Ignore unknown or
	// oversized metadata without preventing delivery of a valid business event.
	if len(parent) != 55 {
		return ctx
	}
	return propagation.TraceContext{}.Extract(ctx, propagation.MapCarrier{"traceparent": parent})
}

func producerSpan(ctx context.Context, topic, parent string) (context.Context, trace.Span) {
	return otel.Tracer("telcopulse/kafka").Start(traceContext(ctx, parent), "publish "+topic, trace.WithSpanKind(trace.SpanKindProducer), trace.WithAttributes(attribute.String("messaging.system", "kafka"), attribute.String("messaging.destination.name", topic), attribute.String("messaging.operation.name", "publish")))
}

// ConsumerSpan creates one processing attempt under the broker record's producer.
// Legacy records without context start a new trace; retries get distinct spans.
func ConsumerSpan(ctx context.Context, record *kgo.Record) (context.Context, trace.Span) {
	parent := ""
	for _, header := range record.Headers {
		if header.Key == "traceparent" {
			parent = string(header.Value)
			break
		}
	}
	return otel.Tracer("telcopulse/kafka").Start(traceContext(ctx, parent), "process "+PurchaseTopic, trace.WithSpanKind(trace.SpanKindConsumer), trace.WithAttributes(attribute.String("messaging.system", "kafka"), attribute.String("messaging.destination.name", PurchaseTopic), attribute.String("messaging.operation.name", "process")))
}
