"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { ArrowUpRight, Search } from "lucide-react";
import { timestamp } from "@/lib/api";
import type { Environment } from "@/lib/contracts";
import { postmortems, type ReportSummary } from "@/lib/postmortems";
import { EmptyState, ErrorState, LoadingState, PageHeader, Panel } from "./common";
import { useEnvironment } from "./providers";
import { Badge } from "./ui/badge";
import { Button } from "./ui/button";
import { Input } from "./ui/input";
import { NativeSelect, NativeSelectOption } from "./ui/native-select";

function ReportCard({ report }: { report: ReportSummary }) {
  const href = `/incidents/${encodeURIComponent(report.incident_id)}#postmortem`;
  return <article className="report-card">
    <div className="report-card-heading">
      <div>
        <div className="report-card-meta"><Badge variant="outline" className={report.severity === "SEV-1" ? "status-error" : report.severity === "SEV-2" ? "status-warning" : "status-neutral"}>{report.severity}</Badge><span>{report.service}</span><span>Published {timestamp(report.generated_at)} WIB</span></div>
        <h3><Link href={href}>{report.incident_title}</Link></h3>
        <p className="report-card-summary">{report.summary}</p>
      </div>
      <Button size="sm" variant="outline" asChild><Link href={href}>Full report <ArrowUpRight data-icon="inline-end" /></Link></Button>
    </div>
    <dl className="report-narrative">
      <div><dt>Root cause</dt><dd>{report.root_cause || "Not recorded"}</dd></div>
      <div><dt>Contributing factors</dt><dd>{report.contributing_factors || "Not recorded"}</dd></div>
      <div><dt>Mitigation</dt><dd>{report.mitigation || "Not included in this older report"}</dd></div>
      <div><dt>What went well</dt><dd>{report.what_went_well || "Not recorded"}</dd></div>
      <div><dt>What went wrong</dt><dd>{report.what_went_wrong || "Not recorded"}</dd></div>
    </dl>
    <footer>Incident <Link href={href} className="table-link mono">{report.incident_id}</Link> · Report from revision {report.incident_version} · Generated by {report.generated_by || "Unknown"}</footer>
  </article>;
}

function ReportList({ environment }: { environment: Environment }) {
  const [serviceInput, setServiceInput] = useState("");
  const [searchInput, setSearchInput] = useState("");
  const [service, setService] = useState("");
  const [search, setSearch] = useState("");
  const [severity, setSeverity] = useState<"" | ReportSummary["severity"]>("");
  const [cursors, setCursors] = useState([""]);
  const cursor = cursors[cursors.length - 1];
  useEffect(() => {
    const timer = window.setTimeout(() => {
      setService(serviceInput.trim());
      setSearch(searchInput.trim());
    }, 250);
    return () => window.clearTimeout(timer);
  }, [serviceInput, searchInput]);
  const query = useQuery({
    queryKey: ["postmortems", environment, service, severity, search, cursor],
    queryFn: () => postmortems.list({ environment, service, severity, search, cursor }),
    refetchOnWindowFocus: false,
  });
  const reset = () => setCursors([""]);
  return <>
    <PageHeader title="RCA reports" description="Search published incident investigations in the selected environment. Report findings are frozen at publication; incident title, service and severity reflect the current incident.">
      <Button variant="outline" asChild><Link href="/rca">Corrective actions</Link></Button>
      <Button variant="outline" onClick={() => void query.refetch()}>Refresh</Button>
    </PageHeader>
    <Panel title="Postmortem library" description="Newest reports first · 10 per page. Open a report for its full timeline, evidence and action items.">
      <div className="table-toolbar report-toolbar">
        <div className="search-field"><Search size={15} /><Input aria-label="Search RCA reports" placeholder="Incident, cause or learning" maxLength={100} value={searchInput} onChange={(event) => { setSearchInput(event.target.value); reset(); }} /></div>
        <Input aria-label="Filter reports by service" placeholder="Exact service name" maxLength={100} value={serviceInput} onChange={(event) => { setServiceInput(event.target.value); reset(); }} />
        <NativeSelect aria-label="Report severity" value={severity} onChange={(event) => { setSeverity(event.target.value as typeof severity); reset(); }}>
          <NativeSelectOption value="">All severities</NativeSelectOption>
          {(["SEV-1", "SEV-2", "SEV-3", "SEV-4"] as const).map((value) => <NativeSelectOption key={value} value={value}>{value}</NativeSelectOption>)}
        </NativeSelect>
        <Button variant="ghost" size="sm" onClick={() => { setServiceInput(""); setSearchInput(""); setService(""); setSearch(""); setSeverity(""); reset(); }}>Clear filters</Button>
      </div>
      {query.isPending ? <LoadingState /> : query.isError ? <div className="panel-padding"><ErrorState error={query.error} retry={() => void query.refetch()} /></div> : query.data.items.length === 0 ? <EmptyState title="No reports in this view" description="Try another service, severity or search term. Reports appear after an incident postmortem is generated." /> : <>
        <div className="report-list">{query.data.items.map((report) => <ReportCard key={report.incident_id} report={report} />)}</div>
        <div className="pagination"><span>Page {cursors.length} · {query.data.items.length} reports shown</span><div><Button size="sm" variant="outline" disabled={cursors.length === 1} onClick={() => setCursors((values) => values.slice(0, -1))}>Previous</Button><Button size="sm" variant="outline" disabled={!query.data.more || !query.data.next} onClick={() => { if (query.data.next) setCursors((values) => [...values, query.data.next!]); }}>Next</Button></div></div>
      </>}
    </Panel>
  </>;
}

export function PostmortemRegister() {
  const { environment } = useEnvironment();
  return <ReportList key={environment} environment={environment} />;
}
