service:
  extensions: [jaeger_storage, jaeger_query]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [jaeger_storage_exporter]
  telemetry:
    logs:
      level: info
extensions:
  jaeger_storage:
    backends:
      local:
        memory:
          max_traces: 5000
  jaeger_query:
    storage:
      traces: local
    http:
      endpoint: 0.0.0.0:16686
receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 256
    spike_limit_mib: 64
  batch:
    timeout: 1s
    send_batch_size: 256
exporters:
  jaeger_storage_exporter:
    trace_storage: local
